### ISSUE TITLE
boombody ruins round starts, entirely

### ISSUE THREAD

**Issue by EntranceJew** [TTT-2/ttt2-wep_boom_body#9] opened 2024-02-04 19:22 UTC
```
[[TTT2] Boom Body [WEAPON]] gamemodes/terrortown/entities/weapons/weapon_ttt_boom_body/shared.lua:80: attempt to call method 'GetTeam' (a nil value)
  1. UpdateRadar - gamemodes/terrortown/entities/weapons/weapon_ttt_boom_body/shared.lua:80
   2. fn - gamemodes/terrortown/entities/weapons/weapon_ttt_boom_body/shared.lua:235
    3. Run - lua/ulib/shared/hook.lua:109
     4. SetRole - gamemodes/terrortown/gamemode/shared/sh_player_ext.lua:146
      5. CleanUp - gamemodes/terrortown/gamemode/server/sv_main.lua:900
       6. unknown - gamemodes/terrortown/gamemode/server/sv_main.lua:970

Timer Failed! [end2prep][@gamemodes/terrortown/gamemode/server/sv_main.lua (line 1294)]

[TTT2 (Base) - v0.12.3b] Warning! A net message (BoomBodyUpdateRadar) is already started! Discarding in favor of the new message! (TTT2RemoveWeaponFromInventory)
  1. RemoveWeaponFromInventoryAndNotifyClient - gamemodes/terrortown/gamemode/server/sv_inventory.lua:36
   2. unknown - gamemodes/terrortown/gamemode/server/sv_weaponry.lua:556

its serial its serial its serial: the game is funny
EntranceJew has restarted the round.
ServerLog: [ULX] EntranceJew has restarted the round.
*DEAD* EntranceJew: !roundrestart
```

```
[[TTT2] Boom Body [WEAPON]] gamemodes/terrortown/entities/weapons/weapon_ttt_boom_body/shared.lua:80: attempt to call method 'GetTeam' (a nil value)
  1. UpdateRadar - gamemodes/terrortown/entities/weapons/weapon_ttt_boom_body/shared.lua:80
   2. fn - gamemodes/terrortown/entities/weapons/weapon_ttt_boom_body/shared.lua:235
    3. Run - lua/ulib/shared/hook.lua:109
     4. SetRole - gamemodes/terrortown/gamemode/shared/sh_player_ext.lua:146
      5. CleanUp - gamemodes/terrortown/gamemode/server/sv_main.lua:900
       6. unknown - gamemodes/terrortown/gamemode/server/sv_main.lua:970

Timer Failed! [end2prep][@gamemodes/terrortown/gamemode/server/sv_main.lua (line 1294)]

[TTT2 (Base) - v0.12.3b] Warning! A net message (BoomBodyUpdateRadar) is already started! Discarding in favor of the new message! (TTT2RemoveWeaponFromInventory)
  1. RemoveWeaponFromInventoryAndNotifyClient - gamemodes/terrortown/gamemode/server/sv_inventory.lua:36
   2. unknown - gamemodes/terrortown/gamemode/server/sv_weaponry.lua:556

Theecoty: kos giga
Theecoty: BITCH ASS T
harkelope has restarted the round.
ServerLog: [ULX] harkelope has restarted the round.
harkelope: !roundrestart
```

```
[[TTT2] Boom Body [WEAPON]] gamemodes/terrortown/entities/weapons/weapon_ttt_boom_body/shared.lua:80: attempt to call method 'GetTeam' (a nil value)
  1. UpdateRadar - gamemodes/terrortown/entities/weapons/weapon_ttt_boom_body/shared.lua:80
   2. fn - gamemodes/terrortown/entities/weapons/weapon_ttt_boom_body/shared.lua:235
    3. Run - lua/ulib/shared/hook.lua:109
     4. SetRole - gamemodes/terrortown/gamemode/shared/sh_player_ext.lua:146
      5. CleanUp - gamemodes/terrortown/gamemode/server/sv_main.lua:900
       6. unknown - gamemodes/terrortown/gamemode/server/sv_main.lua:970

Timer Failed! [end2prep][@gamemodes/terrortown/gamemode/server/sv_main.lua (line 1294)]

[TTT2 (Base) - v0.12.3b] Warning! A net message (BoomBodyUpdateRadar) is already started! Discarding in favor of the new message! (TTT2RemoveWeaponFromInventory)
  1. RemoveWeaponFromInventoryAndNotifyClient - gamemodes/terrortown/gamemode/server/sv_inventory.lua:36
   2. unknown - gamemodes/terrortown/gamemode/server/sv_weaponry.lua:556

...

may!: game broke again ?
CM | Giga: it broked
Theecoty: KOS GIGA
EntranceJew has restarted the round.
ServerLog: [ULX] EntranceJew has restarted the round.
EntranceJew: !roundrestart
```

```
ServerLog: Round ended.
ServerLog: Result: innocents wins.
ERROR!: Can't create physics object for models/gibs/agibs.mdl
TriggerProximity - Missing measure target or measure target with no origin!

[[TTT2] Boom Body [WEAPON]] gamemodes/terrortown/entities/weapons/weapon_ttt_boom_body/shared.lua:80: attempt to call method 'GetTeam' (a nil value)
  1. UpdateRadar - gamemodes/terrortown/entities/weapons/weapon_ttt_boom_body/shared.lua:80
   2. fn - gamemodes/terrortown/entities/weapons/weapon_ttt_boom_body/shared.lua:235
    3. Run - lua/ulib/shared/hook.lua:109
     4. SetRole - gamemodes/terrortown/gamemode/shared/sh_player_ext.lua:146
      5. CleanUp - gamemodes/terrortown/gamemode/server/sv_main.lua:900
       6. unknown - gamemodes/terrortown/gamemode/server/sv_main.lua:970

Timer Failed! [end2prep][@gamemodes/terrortown/gamemode/server/sv_main.lua (line 1294)]

[TTT2 (Base) - v0.12.3b] Warning! A net message (BoomBodyUpdateRadar) is already started! Discarding in favor of the new message! (TTT2RemoveWeaponFromInventory)
  1. RemoveWeaponFromInventoryAndNotifyClient - gamemodes/terrortown/gamemode/server/sv_inventory.lua:36
   2. unknown - gamemodes/terrortown/gamemode/server/sv_weaponry.lua:556

...

CM | Giga: ANY time nosa calls for dna it's a decoy lol
Nosa: pretty much
Nosa: but I died to rdm
Theecoty: server broke
CM | Giga: oop
*DEAD* PB&J☺: yeah
may!: coty broke
Clamping SetLocalVelocity(869.302429,-982.631592,-9227.956055) on gmod_hands
EntranceJew has restarted the round.
ServerLog: [ULX] EntranceJew has restarted the round.
EntranceJew: !roundrestart
```

**Comment by TimGoll** [comment] 2024-02-04 20:43
How does this happen? did you place a boombody and then the round ended? or how?

**Comment by mexikoedi** [comment] 2024-02-08 18:38
I also experienced this issue on my server.
When the boom body is placed and the round ends then the new round doesn't start.
The above error is also shown and only a manual round restart fixed the situation.

**Comment by TimGoll** [comment] 2024-02-08 18:39
> I also experienced this issue on my server. When the boom body is placed and the round ends then the new round doesn't start. The above error is also shown and only a manual round restart fixed the situation.

Thanks this is the info I needed so I can attempt to fix it. The above errors were pretty helpless

**Comment by EntranceJew** [comment] 2024-02-08 18:44
well, next time make the code die in a more convenient spot :V

**Comment by TimGoll** [comment] 2024-02-14 13:46
Phew it seems hard to fix right now. Sometimes the owner entity seems to be an entity where you can't call GetTeam(). I can add a safeguard to make sure it is always valid. My guess would be that the owner disconnected and therefore the issue is caused

**Comment by mexikoedi** [comment] 2024-02-14 14:11
In our round everyone was still connected.
Some were already dead and therefore spectator but otherwise everything else seemed "normal" as always so not sure why this happened.
Can't remember this issue before, so it may be be a new issue or it's a "rare" issue.
Either way a safeguard sounds good.
Or remove/"deactivate" the boom body at round end or something similar?

**Comment by TimGoll** [comment] 2024-02-14 14:19
I added a safeguard and I'll push it to the workshop right now. So this should be fixed, please reopen if the issue persists.

Just a note: Once ttt2 v0.13 is released, the boom body will use marker vision as well and the cause for this issue is removed anyway

**Closed as completed by TimGoll** 2024-02-14 14:19 UTC

**Comment by TimGoll** [comment] 2024-02-14 19:43
![image](https://github.com/TTT-2/ttt2-wep_boom_body/assets/13639408/81adec23-3ab3-466b-8f51-a7a52039f650)

Coming soon...
